font_size = 10

# https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets
harfbuzz_features = ["ss01", "ss02", "ss03", "ss04", "ss06", "zero", "onum"]

[[font.font]]
family = "Fira Code"

# Ubuntu

[colors]
foreground = "#eeeeec"
background = "#300a24"
cursor_bg = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#b5d5ff"
selection_fg = "#000000"

ansi = ["#2e3436","#cc0000","#4e9a06","#c4a000","#3465a4","#75507b","#06989a","#d3d7cf"]
brights = ["#555753","#ef2929","#8ae234","#fce94f","#729fcf","#ad7fa8","#34e2e2","#eeeeec"]
