[user]
name = "Rain"
email = "rain@sunshowers.io"

[ui]
default-command = "sl"
diff.tool = ["difft", "--color=always", "$left", "$right"]

[aliases]
sl = ["log", "-r", "open()"]
slog = ["log", "-r", "open()", "-T", "builtin_log_detailed"]
sq = ["squash"]

[revsets]
# log = 'open()'

[git]
auto-local-branch = false

[revset-aliases]
# See https://github.com/martinvonz/jj/blob/main/docs/revsets.md
#
# We're uninterested in remote branches from origin etc, and their ancestors. But we *are*
# interested in @git remote branches.
#
# What if a commit is present in both @git and a remote branch? In that case we are interested in
# the commit. In the below computation, the commit is present in both `remote_branches()` and
# `git_branches()`, and so it is not part of `uninterested()`. This is the desired behavior.
'git_branches()' = 'remote_branches(remote=exact:"git")'
'uninterested()' = '::(remote_branches() ~ git_branches())'
'mine()' = 'author("rain@") | author("rain1@")'
'interested()' = 'mine() ~ uninterested()'
'open()' = '''
    ancestors(interested(), 2)
      | (immutable_heads() ~ tags())
      | ancestors(@, 2)
'''

[templates]
log = 'builtin_log_comfortable'
