[user]
name = "Rain"
email = "rain@sunshowers.io"

[ui]
default-command = "sl"
#diff.tool = ["difft", "--color=always", "$left", "$right"]

[aliases]
aa = ["amend"]
bs = ["branch", "set", "-r", "@-"]
a = ["describe", "@-"]
sl = ["log", "-r", "open()"]
slog = ["log", "-r", "open()", "-T", "builtin_log_detailed"]
sq = ["squash"]

[revsets]
# log = 'open()'

[revset-aliases]
# See https://github.com/martinvonz/jj/blob/main/docs/revsets.md
'uninterested()' = '::remote_branches() | tags()'
'mine()' = 'author("rain@") | author("rain1@")'
'interested()' = 'mine() ~ uninterested()'
'open()' = '''
    ancestors(interested(), 3)
      | (immutable_heads() ~ tags())
      | ancestors(@, 3)
'''

[templates]
log = 'builtin_log_comfortable'
